version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongoEmpresaContaner
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: noSql
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: empresaDB
    ports:
      - 27018:27017
    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongoExpress1
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: noSql
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: noSql
      ME_CONFIG_BASICAUTH_PASSWORD: 123
    ports:
      - 8082:8081

volumes:
  mongodata:
    driver: local